### ISSUE TITLE
SenseCAP S2120(Weather Station) Detail Page

### ISSUE THREAD

**Issue by CropWatchDevelopment** [CropWatchDevelopment/CropWatch#65]
We use the Seeed Weather Station ([link](https://www.seeedstudio.com/sensecap-s2120-lorawan-8-in-1-weather-sensor-p-5436.html)

This device provides 8 data points not including signal strength or battery level:

1. Air Temperature
2. Air Humidity
3. Air Pressure
4. Rain fall
5. Wind Speed
6. Wind Direction
7. UV
8. LUX (light intensity)

I love how the Temp/Humidity sensor page works, and instead of having the background circle change colors based on temp, I am wondering if we could have that be a compas and show the wind direction!
Possibly using a CSS [rotate()](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate) ?

![image](https://github.com/CropWatchDevelopment/CropWatch/assets/111664979/2ef27a80-6b30-4271-8fb9-4d03cd3de711)

I think that may be cool as it pushes the temp, humidity, wind direction all into one small area (maybe use the wind speed as the bigger letters, and put temp under it... not sure what would look best what are your ideas @jramiroz98 ?

**Comment by jramiroz98** [comment]
<img width="271" alt="Screen Shot 2024-05-25 at 10 26 02 PM" src="https://github.com/CropWatchDevelopment/CropWatch/assets/80351867/03a92f8d-1eed-4c5c-8ba0-019dd265ace7">
what are your thoughts?

**Comment by jramiroz98** [comment]
should be E not NE 
sorry for my mistake, was testing on the NE position before

**Comment by CropWatchDevelopment** [comment]
NO worries I understand ;)

**Comment by jramiroz98** [comment]
#72 Wheather knob has been added
Only missing remaining data cards

**Comment by CropWatchDevelopment** [comment]
Merged and awesome :D
