### ISSUE TITLE
Editing Location Name wipesout location name

### ISSUE THREAD

**Issue by CropWatchDevelopment** [CropWatchDevelopment/CropWatch#78]
When entering a location name, it failes to save with the error ```location_id required```

![image](https://github.com/CropWatchDevelopment/CropWatch/assets/111664979/cdc99b7a-089f-4b38-86fc-52cf6cc976f6)

**Comment by CropWatchDevelopment** [comment]
Fixed with commit: https://github.com/CropWatchDevelopment/CropWatch/commit/844e61356b4f76f9cde02891719fd27f7cf44b99

**Comment by sayakaikemizu** [comment]
It's Fixed!
