### ISSUE TITLE
History page fails to load hostory points, endpoint changed

### ISSUE THREAD

**Issue by CropWatchDevelopment** [CropWatchDevelopment/CropWatch#79]
History page fails to load datapoints as the endpoint shoudl be pulling from the latest endpoint.

![image](https://github.com/CropWatchDevelopment/CropWatch/assets/111664979/d633a265-6e6c-4e0b-baa2-fdbf8eb3d4de)

**Comment by CropWatchDevelopment** [comment]
Fix submitted with PR#88 (https://github.com/CropWatchDevelopment/CropWatch/pull/88/commits/256802b70bb840baf9a429f0269097fa3cbebb2d)
@sayakaikemizu Ready for QA

**Comment by sayakaikemizu** [comment]
It's Fixed!
