### ISSUE TITLE
sign up page isn't working

### ISSUE THREAD

**Issue by sayakaikemizu** [CropWatchDevelopment/CropWatch#94]
![img_9055_720](https://github.com/CropWatchDevelopment/CropWatch/assets/166083102/b5600a20-d297-43d0-9273-142891046971)

**Comment by CropWatchDevelopment** [comment]
Latest pushed to prod @sayakaikemizu QA again.

**Comment by CropWatchDevelopment** [comment]
@sayakaikemizu Ready for QA again

**Comment by sayakaikemizu** [comment]
- Worked at google e mail. I haven't checked using other email address. 
- Sent e-mail was in the junk mail

**Comment by CropWatchDevelopment** [comment]
Nothing we can do about email going into Junk.
